export const LOGIN_SUCC = 'login_succ'
export const LOGIN_ERR = 'login_err'
export const UPDATE_SUCC = 'update_succ'
export const RESET_USER = 'reset_user'
export const GET_USERLIST_SUCC = 'get_userlist_succ'
export const ADD_CHAT = 'add_chat'
export const GET_ALLCHATS_SUCC = 'get_allchats_succ'
export const READ_CHAT_SUCC = 'read_chat_succ'
